source 'https://github.com/blodely/LYSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

use_frameworks!

target 'LYCompLayout_Example' do
	pod 'LYCompLayout', :path => '../'

	target 'LYCompLayout_Tests' do
		inherit! :search_paths
    
	end
end
